package lab

import (
	"bytes"
	"fmt"
	"strconv"
	"text/template"
	"time"
)

// Stick-table names used by every lab node. LabTable is fed only by the
// isolated lab listener, whose keys come from the synthetic ClientHeader.
// ProdTable is fed only by the production-style listener, whose keys come
// from the real connection source. ProxyTable is fed only by the
// PROXY-protocol listener, which runs the unchanged production key rule
// against a source address the harness declares in a PROXY header.
const (
	LabTable   = "lab_in"
	ProdTable  = "prod_in"
	ProxyTable = "proxy_in"
)

// HTTP headers exchanged between the harness, HAProxy, and the responder.
const (
	// ClientHeader carries the synthetic client address on the lab listener.
	// HAProxy trusts it only there; the production-style listener ignores it.
	ClientHeader = "X-Lab-Client"
	// RequestIDHeader carries the harness-assigned unique request ID.
	RequestIDHeader = "X-Lab-Request-Id"
	// NodeHeader is set by HAProxy to the node name before forwarding.
	NodeHeader = "X-Lab-Node"
	// ListenerHeader is set by HAProxy to "lab", "prod", or "proxy" before
	// forwarding.
	ListenerHeader = "X-Lab-Listener"
	// KeyHeader is set by HAProxy to the tracked key on the forwarded
	// request and on the response.
	KeyHeader = "X-Lab-Key"
	// LookupHeader is set by HAProxy on the response to the http_req_cnt it
	// looks up with the same key expression used for tracking.
	LookupHeader = "X-Lab-Lookup-Cnt"
)

// ExpiryFactor is how many rate periods a table entry outlives its last
// update. Decay tests need entries to survive more than two periods.
const ExpiryFactor = 3

// configParams feeds configTemplate. Listener fields are HAProxy bind
// addresses; the lab binds inherited sockets with fd@N so no port is ever
// chosen by probing and released.
type configParams struct {
	Node        string
	Socket      string
	LabBind     string
	ProdBinds   []string
	ProxyBind   string
	Responder   string
	PeriodMS    string
	ExpireMS    string
	LabTable    string
	ProdTable   string
	ProxyTable  string
	ClientHdr   string
	NodeHdr     string
	ListenerHdr string
	KeyHdr      string
	LookupHdr   string
}

// The key expression is stored once in txn.lab_key and reused for tracking,
// lookup, and the forwarded key header, so tracking and lookup can never use
// different keys. Both listeners mask IPv6 to /64 and keep IPv4 at /32. The
// table has no peers section: nodes never replicate input counters.
var configTemplate = template.Must(template.New("haproxy.cfg").Parse(`# Generated by the haproxy-table-aggregator lab for node {{.Node}}.
global
    nbthread 1
    maxconn 256
    zero-warning
    stats socket {{.Socket}} mode 600 level admin
    stats timeout 10s

defaults
    mode http
    retries 0
    timeout connect 2s
    timeout client 10s
    timeout server 10s

backend {{.LabTable}}
    stick-table type ipv6 size 1k expire {{.ExpireMS}} store http_req_cnt,http_req_rate({{.PeriodMS}})

backend {{.ProdTable}}
    stick-table type ipv6 size 1k expire {{.ExpireMS}} store http_req_cnt,http_req_rate({{.PeriodMS}})

backend {{.ProxyTable}}
    stick-table type ipv6 size 1k expire {{.ExpireMS}} store http_req_cnt,http_req_rate({{.PeriodMS}})

# Isolated lab listener: the synthetic client header is trusted here only.
frontend lab
    bind {{.LabBind}}
    http-request set-var(txn.lab_key) req.hdr_ip({{.ClientHdr}}),ipmask(32,64) if { req.hdr_cnt({{.ClientHdr}}) eq 1 }
    http-request deny deny_status 400 unless { var(txn.lab_key) -m found }
    http-request track-sc0 var(txn.lab_key) table {{.LabTable}}
    http-request set-header {{.NodeHdr}} {{.Node}}
    http-request set-header {{.ListenerHdr}} lab
    http-request set-header {{.KeyHdr}} %[var(txn.lab_key)]
    http-after-response set-header {{.LookupHdr}} %[var(txn.lab_key),table_http_req_cnt({{.LabTable}})]
    http-after-response set-header {{.KeyHdr}} %[var(txn.lab_key)]
    default_backend responder

# Production-style listener: keys come from the source address only.
frontend prod
{{- range .ProdBinds}}
    bind {{.}}
{{- end}}
    http-request set-var(txn.lab_key) src,ipmask(32,64)
    http-request track-sc0 var(txn.lab_key) table {{.ProdTable}}
    http-request set-header {{.NodeHdr}} {{.Node}}
    http-request set-header {{.ListenerHdr}} prod
    http-request set-header {{.KeyHdr}} %[var(txn.lab_key)]
    http-after-response set-header {{.LookupHdr}} %[var(txn.lab_key),table_http_req_cnt({{.ProdTable}})]
    http-after-response set-header {{.KeyHdr}} %[var(txn.lab_key)]
    default_backend responder

# PROXY-protocol listener: the production key rule, unchanged, fed with
# arbitrary IPv4/IPv6 sources declared by the harness. Accepting PROXY from
# any client is a test-only trust confined to this loopback listener; a
# deployment accepts it only from its own load balancers, if at all.
frontend proxy
    bind {{.ProxyBind}} accept-proxy
    http-request set-var(txn.lab_key) src,ipmask(32,64)
    http-request track-sc0 var(txn.lab_key) table {{.ProxyTable}}
    http-request set-header {{.NodeHdr}} {{.Node}}
    http-request set-header {{.ListenerHdr}} proxy
    http-request set-header {{.KeyHdr}} %[var(txn.lab_key)]
    http-after-response set-header {{.LookupHdr}} %[var(txn.lab_key),table_http_req_cnt({{.ProxyTable}})]
    http-after-response set-header {{.KeyHdr}} %[var(txn.lab_key)]
    default_backend responder

backend responder
    server responder {{.Responder}}
`))

func renderConfig(p configParams) ([]byte, error) {
	var buf bytes.Buffer
	if err := configTemplate.Execute(&buf, p); err != nil {
		return nil, fmt.Errorf("render haproxy config: %w", err)
	}
	return buf.Bytes(), nil
}

func millis(d time.Duration) string {
	return strconv.FormatInt(d.Milliseconds(), 10)
}
